services:
  comfyui:
    image: nvcr.io/nvidia/cuda:11.8.0-base-ubuntu22.04
    volumes:
      - /home/work:/work
    command:
    - /bin/bash
    - -c
    - |
      apt update
      DEBIAN_FRONTEND=noninteractive apt install -y tzdata
      apt install -y git python3-pip libgl1-mesa-dev libglib2.0-0 python3-tk libcusparse-11-8  libcurand-11-8
      update-alternatives --install /usr/bin/python python /usr/bin/python3 1
      update-alternatives --config python
      cd /work/diffusion/kohya_ss/
      ./setup.sh
      ./gui.sh --listen 0.0.0.0 --server_port 7860
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    tty: true
    stdin_open: true
    ports:
      - "7860:7860"
    environment:
      TZ: "Asia/Tokyo"
