services:
  comfyui:
    image: nvcr.io/nvidia/tensorrt:24.06-py3
    volumes:
      - ./ComfyUI:/ComfyUI
      - /home/work:/work
    command:
    - /bin/bash
    - -c
    - |
      apt update
      apt install -y git python3-pip libgl1-mesa-dev libglib2.0-0
      pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
      cd /ComfyUI/
      pip install -r requirements.txt
      python main.py --listen
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
    ports:
      - "8188:8188"
